### ISSUE TITLE
LGTM.com - false positive C/C++ comparison with wider type

### ISSUE THREAD

**Issue by andyhhp** [Semmle/ql#3247]
https://lgtm.com/projects/g/TrenchBoot/landing-zone/snapshot/164a7bcef098d7352fa3731e5392a2109491a9f0/files/dev.c?sort=name&dir=ASC&mode=heatmap#x203928dc5733003b:1

Paraphrasing, it has found:
```
u32 dev_caps = ...;
for (u8 i = 0; i < DEV_CAP_MAPS(dev_cap); i++)
    ...
```
The statement about different types is technically true (as it only discusses types), but unhelpful.

The macro `DEV_CAP_MAPS()` is:
```
#define DEV_CAP_MAPS(c) ((c & 0xFF0000) >> 16)
```
so while the type is larger than u8, its range is restricted to that of u8, so no overflow can occur as a consequence.

There are plenty of ways to rewrite `DEV_CAP_MAPS()` so LGTM would be happy with it, most obviously `(u8)(c >> 16)`, but the above expression is very common in embedded C, so it would be more helpful to adjust the check to take into account any range restrictions, rather than just considering type.

**Comment by geoffw0** [comment]
Fixed by https://github.com/Semmle/ql/pull/3277.  Please allow up to / approximately two weeks for this change to reach LGTM.

**Comment by andyhhp** [comment]
oh - thanks!  I'll check back in 2 weeks

**Comment by andyhhp** [comment]
I've checked back, and there seems to be an issue with the aggregated stats.

https://lgtm.com/projects/g/TrenchBoot/landing-zone/?mode=list is the overall view, claiming that these two issues are still present, but the report of the specific build https://lgtm.com/projects/g/TrenchBoot/landing-zone/rev/1cb62399b2ef9547681ecb1be85d03b43ba10cbd correctly identifies 0 issues.

What provision is there for deleting alerts which have disappeared due to bugfixes in LGTM itself?

**Comment by geoffw0** [comment]
Link to follow-up ticket: https://discuss.lgtm.com/t/dashboard-retains-false-positive-alerts-after-theyve-been-fixed/2888

Sorry I'm not able to help with the dashboard issue, I'm trying to get someone else to look into it.
